apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "media-portal.fullname" . }}
  labels:
    {{- include "media-portal.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "media-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "media-portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: NODE_ENV
          value: {{ .Values.env.nodeEnv | quote }}
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-api-key
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-auth-domain
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-project-id
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-storage-bucket
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-messaging-sender-id
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-app-id
        - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: firebase-measurement-id
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: spotify-client-id
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: spotify-client-secret
        - name: NEXTAUTH_URL
          value: {{ .Values.env.nextauthUrl | quote }}
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "media-portal.fullname" . }}
              key: nextauth-secret
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
