apiVersion: v1
kind: Service
metadata:
  name: {{ include "media-portal.fullname" . }}
  labels:
    {{- include "media-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "media-portal.selectorLabels" . | nindent 4 }}
