apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-portal
  labels:
    app: media-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-portal
  template:
    metadata:
      labels:
        app: media-portal
    spec:
      containers:
      - name: media-portal
        image: eggystrone/media-portal:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_FIREBASE_API_KEY
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-api-key
        - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-auth-domain
        - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-project-id
        - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-storage-bucket
        - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-messaging-sender-id
        - name: NEXT_PUBLIC_FIREBASE_APP_ID
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-app-id
        - name: NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: firebase-measurement-id
        - name: SPOTIFY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: spotify-client-id
        - name: SPOTIFY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: spotify-client-secret
        - name: NEXTAUTH_URL
          valueFrom:
            configMapKeyRef:
              name: media-portal-config
              key: nextauth-url
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: media-portal-secrets
              key: nextauth-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
