apiVersion: v1
kind: Service
metadata:
  name: media-portal
  labels:
    app: media-portal
spec:
  type: LoadBalancer
  selector:
    app: media-portal
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
